### ISSUE TITLE
警告：这个插件会直接修改源文件

### ISSUE THREAD

**Issue by sisyphsu** [xu-song/hexo-auto-category#11]
试用了一下，发现这个插件直接把所有文档的页头全部改了一遍。
包括date的格式、tags与categories的格式以及顺序，相当于整体格式化。
如果你是强迫症的话，这种格式化会非常烦人，我试用之前忘记备份原始文件，只好可怜的一个个再改回来。。。

可以使用`hexo-directory-category`这个插件，它没有直接修改源文件。

请作者增加一个警告，告诉其他人，你的插件会修改MarkDown源文件，其中的风险起码应该告知用户。

**Comment by xu-song** [comment]
写了  https://github.com/xu-song/hexo-auto-category#warning

**Comment by sisyphsu** [comment]
@xu-song 警告只写了会复写categories，但是执行之后它把整个文档顶部都改了。

- 文档日期被后缀00:00:00。
- tags从单行数组[a, b, c]改成多行数组。
- time、tags、categories的排序也改变了。

这就类似于代码格式化，你感觉不错or标准的格式，其他人可能很不喜欢。

**Comment by xu-song** [comment]
嗯，尽快加上，谢谢反馈

**Comment by BitMindLab** [comment]
sss
====

ss

ssss
======
