### ISSUE TITLE
How do I create files in subdirectories？

### ISSUE THREAD

**Issue by yansheng836** [xu-song/hexo-auto-category#12]
Just like how to create this file `source/_post/web/framework/hexo.md` with terminal?

**Comment by xu-song** [comment]
```
mkdir -p source/_post/web/framework/
touch source/_post/web/framework/hexo.md
```

**Comment by yansheng836** [comment]
Thanks, I have tried in this way. It will make a new file in the subdirectories, but it can't generate the `Front-matter` of the file that what I want. Do you have ang other way to solve the problem , just like the `hexo new file`?

What I test just like:
```bash
$ hexo new "web/hexo"
INFO  Created: H:\Hexo\source\_posts\web-hexo.md

$ hexo new "web//hello"
INFO  Created: H:\Hexo\source\_posts\web-hello.md

#The following two commands will report exceptions
$ hexo new "web\world"
$ hexo new "web\\world"
```

**Comment by xu-song** [comment]
As far as I know, `hexo new` does not support subdirectory.
I write the `front-matter` by myself

**Comment by yansheng836** [comment]
Ok, I see. Thank you.
