### ISSUE TITLE
_Post.md 可以指定生成分类目录需要几层吗?

### ISSUE THREAD

**Issue by nondevops** [xu-song/hexo-auto-category#15]
_Post.md 可以指定生成分类目录需要几层吗?

在站点配置文件配置后,的确作用了_post的目录,不过我想在站点配置文件配置的是目录层级为2的情况下.想某些目录不需要过深的层级显示,比如我只想显示python-nomrmal这一层就截止,不要把下级目录生成出来, 
![image](https://user-images.githubusercontent.com/12181410/69633642-9684b700-108b-11ea-977f-fe39ac2f82cf.png)

我手动在index.md定义这个属性,测试无效,true false 都试过
![image](https://user-images.githubusercontent.com/12181410/69633817-e82d4180-108b-11ea-975f-f897624b48bc.png)

@xu-song

**Comment by xu-song** [comment]
这个配置是放在 `_config.yml`中的。

> 某些目录不需要过深的层级显示

暂时不支持该需求，建议调整目录结构
