### ISSUE TITLE
文章标题解析不成功

### ISSUE THREAD

**Issue by wangtaocs** [xu-song/hexo-auto-category#18]
![image](https://user-images.githubusercontent.com/60781124/77249596-4a363600-6c7d-11ea-969d-755b2f7d5b19.png)
![image](https://user-images.githubusercontent.com/60781124/77249605-5a4e1580-6c7d-11ea-8cba-8a2ab78697a2.png)
文章标题里的目录名怎么去掉呢

**Comment by xu-song** [comment]
标题里不会有目录名啊，什么操作系统

**Comment by wangtaocs** [comment]
谢谢您的回复，我已经解决了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Xu Song <notifications@github.com>
发送时间: Monday, March 30, 2020 12:23:32 PM
收件人: xu-song/hexo-auto-category <hexo-auto-category@noreply.github.com>
抄送: wangtaocs <wangtaocs@outlook.com>; Author <author@noreply.github.com>
主题: Re: [xu-song/hexo-auto-category] 文章标题解析不成功 (#18)


标题里不会有目录名啊，什么操作系统

―
