### ISSUE TITLE
这真是一个很好👍插件，有问题请教下，不甚感激！

### ISSUE THREAD

**Issue by GanZhiXiong** [xu-song/hexo-auto-category#22]
这不是issue，由于此问题我亟待解决，所以我在这里请教下各位。
如果长时间没人回答，我会关掉此问题。

- 问题1
`hexo new --path go/hello world "hello world"` 将会在 `source/_posts/go/` 目录下生成 `hello world.md`文件，并且标题为”hello world”。但是我想省略命令中的"hello world”, 让文件名自动生成标题该如何写呢？

- 问题2
`hexo new --path go/hello world "hello world"`  如分类层级较多，比如 `编程语言/后端/go`，每次在go下创建md文件都要写全路径，这种方式比较影响效率，有没有像cd目录名称带提示的方法呢？

**Comment by zyu0** [comment]
问题一我也没解决，有找过脚本，但那是用来给已存在的大量文档写front matter的，不太适合新文件，而且没琢磨明白那脚本怎么用的……
问题二我是通过另一个笔记软件实现的，obsidian，新建文件就不用命令来建了，用obsidian来控制文档库，很方便，而且可以设置模板文件来统一插入front matter

**Comment by xu-song** [comment]
`hexo new`的源码在 https://github.com/hexojs/hexo/blob/master/lib/plugins/console/new.js
问题一二这俩功能，应该都要在这里做修改

**Comment by EsunR** [comment]
可以自行写脚本代替 hexo new 指令，提供一个个人使用的参考：
```sh
#!/bin/sh

scriptDir=$(
    cd "$(dirname "$0")"
    pwd
)
postDir=$(
    cd "$scriptDir/../source/_posts"
    pwd
)

read -p "请输入文章标题：" postTitle
read -p "请输入文章分类(多级分类中间用『/』分割)：" postCategory

postFileName=$(echo $postTitle | tr ' ' '-')

# 判断 postDir 目录下是否有对应的文章分类文件夹，否则创建
if [ ! -d "$postDir/$postCategory" ]; then
    mkdir -p "$postDir/$postCategory"
fi

currentTime=$(date "+%Y-%m-%d %H:%M:%S")

# 创建 markdown 文件
cat >$postDir/$postCategory/$postFileName.md <<EOF
---
title: $postTitle
tags: []
categories:
$(
    for category in $(echo $postCategory | tr '/' ' '); do
        echo "  - $category"
    done
)
date: $currentTime
---
EOF

echo "文件创建成功!"
echo "$postDir/$postCategory/$postFileName.md"
```

**Comment by GanZhiXiong** [comment]
这个问题，我现在也不需要解决了。

因为写文章之前应该是写草稿，也就是文章先放到 `_drafts` 目录，文章编写完成后，再移动到 `_posts` 目录。这才是标准的流程。

好处就是：未写完的文章，放到 `_drafts` 目录，防止被发布，尤其是使用自动化部署时。

**Comment by GanZhiXiong** [comment]
感谢各位！🤝
