### ISSUE TITLE
您好，npm是否可以重新发布一下

### ISSUE THREAD

**Issue by zyu0** [xu-song/hexo-auto-category#23]
npm安装还存在那个 err: TypeError: tmpPost.categories.join is not a function 的问题，翻了下issues才发现已经修复了

**Comment by xu-song** [comment]
#19 新版已经发布，可以运行下面命令更新
```
npm update hexo-auto-category
```

**Comment by zyu0** [comment]
已安装，非常感谢

**Comment by xu-song** [comment]
感谢关注，欢迎提各种宝贵意见
