### ISSUE TITLE
重命名文件夹文章内容丢失

### ISSUE THREAD

**Issue by fanmore** [xu-song/hexo-auto-category#26]
使用hexo 6.2.0测试发现，本地启动后，直接更改文件夹名称，下面的所有文章内容丢失

**Comment by xu-song** [comment]
没遇到过。
这问题能复现吗？

**Comment by fanmore** [comment]
有可能是环境问题，使用的windows系统，编辑工具使用的VsCode，在使用重命名文件夹的时候，控制台会出现文件已存在的错误信息，然后就会出现内容丢失的情况

**Comment by johnsonlee** [comment]
same issue
