### ISSUE TITLE
插件会将_draft下的目录生成分类

### ISSUE THREAD

**Issue by yehuohan** [xu-song/hexo-auto-category#3]
_draft下的目录也生成了分类，使用`hexo s`预览时，或是部署到github page上，都将_draft下的目录生成分类。
附：我使用的是0.1.5的最新版本。

**Comment by xu-song** [comment]
你的draft目录也生成了 html页面吗？

**Comment by xu-song** [comment]
是的，我check一下，thanks

**Comment by yehuohan** [comment]
ok~~

**Comment by xu-song** [comment]
你更新一下
```
npm update
```

当`_config.yml` 中的配置是

- `render_drafts: true`时，会对`_drafts`目录生成`categories`。
- `render_drafts: false`时，不会对`_drafts`目录生成`categories`。

**Comment by yehuohan** [comment]
好的~~，已经正常了。
