### ISSUE TITLE
通过Github Action自动部署时没有起作用

### ISSUE THREAD

**Issue by liunaijie** [xu-song/hexo-auto-category#32]
我在本地测试可以成功分类
但是通过Github Action自动部署时，却发现没有起作用。
通过log查看，已经运行改代码
```
INFO  Generated: categories [life] for post [hello_world.md]
```
但是在输出文件中，没有category文件夹。
如果手动添加category则可以产生category文件夹。

Github action log for your refer:
https://github.com/liunaijie/liunaijie.github.io/actions/runs/6027436406/job/16352635372

click `hexo deploy` to see the detail.

**Comment by xu-song** [comment]
日志看上去有 
```
INFO  Generated: categories [coding,algorithm] for post [布隆过滤器.md]
INFO  Generated: categories [coding,algorithm] for post [数组.md]
INFO  Generated: categories [coding,algorithm] for post [树的几种遍历方式.md]
INFO  Generated: categories [coding,algorithm] for post [用单链表简单实现LRU算法.md]
INFO  Generated: categories [coding,algorithm] for post [算法与数据结构.md]
INFO  Generated: categories [coding,algorithm] for post [链表.md]
```

最后结果没有吗？

**Comment by liunaijie** [comment]
是的
从后面的log里只有手动填写的category才会生成html, 通过这个插件生成的category都不会生成html页面
```
Generated: categories/coding/web3/index.html
```

在这个action里, 我将`npm install hexo-auto-category --save`命令与`hexo g`放到一起 不生效,之前放到不同的step里也不生效

我后面运行`git status`命令, 没有看到md文件的改动, 感觉是没有覆盖, 重写成功.
