### ISSUE TITLE
文件夹更名后文章内容被清空

### ISSUE THREAD

**Issue by uuanqin** [xu-song/hexo-auto-category#36]
例如，当进行以下操作时，文件夹下所有的文章内容会被清空：
1. _posts目录下存在一个文件夹，如：`test11`。文件夹下有文章`test.md`
2. hexo三连：`hexo clean && hexo g && hexo s`。
![image](https://github.com/xu-song/hexo-auto-category/assets/61202052/628db32e-8ac9-4d24-b602-f322f6a0ee80)
3. 此时更改文件夹的名字：`test 11 22`。热更新后，重命名后的文件夹下所有的文章内容均被清空。
![image](https://github.com/xu-song/hexo-auto-category/assets/61202052/ea6014f9-ccf0-4f9f-87f1-ec0371c40476)

日志：
```
INFO  Generated: categories [[ 'test 11 22' ]] for post [test.md]
WARN  Trying to "create" _posts/test 11 22/test.md, but the file already exists!
INFO  No title found for post [source/_posts/test 11 22/test.md][  ]
INFO  Generate link [0] for post [source/_posts/test 11 22/test.md][  ]
INFO  Generated: categories [undefined] for post [source/_posts/test 11 22/test.md][  ]
INFO  Generated: categories [[ 'test 11 22' ]] for post [test.md]
INFO  No title found for post [source/_posts/test 11 22/test.md][  ]
INFO  Generate link [0] for post [source/_posts/test 11 22/test.md][  ]
INFO  Generated: categories [[ 'test 11 22' ]] for post [source/_posts/test 11 22/test.md][  ]

```

不知道是不是和文件名空格有关，尝试复现这个问题的时候只在某些情况下复现成功。最初发现这个 Bug 是 hexo s 执行后，我把名为 `out of date` 的文件夹，改为 `OutOfDate` 之后，`OutOfDate` 下的所有文章被清空。

**Comment by xu-song** [comment]
是解决了吗？
