### ISSUE TITLE
Action部署不生效？

### ISSUE THREAD

**Issue by miaoyanginfo** [xu-song/hexo-auto-category#37]
小白求助，我的hexo是使用github action生成page这样部署的，在本地测试的时候正常。但上传到github后就不生效了。是不是因为github action无法回写文件造成的呢？有没有好的解决方法呢？

**Comment by xu-song** [comment]
我对github action不熟唉，看日志能看出什么来吗？

**Comment by miaoyanginfo** [comment]
我看了下日志没有报错。插件运行之后是会在原有的日志md文件中增加categories字段是吗，还是在生成的静态文件中做处理呢？

**Comment by xu-song** [comment]
是在原md文件中增加categories字段

**Comment by miaoyanginfo** [comment]
好的明白了，那可能就是github 的action无法回写源日志文件造成的。谢谢

**Comment by xu-song** [comment]
👍
