### ISSUE TITLE
预览时，是一直在处理md文件吗？

### ISSUE THREAD

**Issue by yehuohan** [xu-song/hexo-auto-category#4]
我使用hexo s预览后，同时编辑md文件时，不时的显示文件已经修改，是否加载更新之类的对话框。

**Comment by xu-song** [comment]
```sh
$ hexo clean && hexo g && hexo s
```
这顺序执行也有问题吗？

**Comment by yehuohan** [comment]
刚试了一下，也会有。

**Comment by xu-song** [comment]
什么log，我这儿没出现这种问题。

**Comment by yehuohan** [comment]
因为有图片，我发你邮箱了eson.org@gmail.com

**Comment by xu-song** [comment]
强大的issue可以用图片的，直接拖进来就行。

已看邮件，但是我暂时没重现你遇到的情况

**Comment by yehuohan** [comment]
学习了，之前查issue放图片，都说用图床~ ~尴尬~~

**Comment by yehuohan** [comment]
你那边也会一直出这下面图片中那样的INFO。。吗？
![3](https://user-images.githubusercontent.com/17680752/38231060-7cae927e-3743-11e8-84b8-7f09494365a3.PNG)

**Comment by xu-song** [comment]
我checkout了你的[项目--杂记目录](https://github.com/yehuohan/yehuohan.blog.src)，并未重现到这个`重复generate`的问题。

倒是遇到下面的问题。
```
Error: [pandoc warning] YAML header is not an object "source" (line 3, column 1)
```

**Comment by yehuohan** [comment]
好的，我在看看，我先关闭issue了

**Comment by xu-song** [comment]
我checkout你的杂技目录，hexo g发现有error。稍后我再仔细 check一下

**Comment by yehuohan** [comment]
好的，麻烦了~

**Comment by xu-song** [comment]
你用之前版本有这问题吗？
```
npm install --save hexo-auto-category@0.1.5
```

**Comment by yehuohan** [comment]
也有，也是同样的问题，控制台一直出现INFO。。。那个信息。
附：npm安装0.1.5后，也是先hexo g再hexo s

**Comment by xu-song** [comment]
讲道理，`hexo g`成功后，`hexo s`阶段就不会打印`Generatd: categories ...`的log，即不再调用`hexo-auto-category`。

@JLHwung  请大神确认一下 上述关于`hexo s 逻辑`的理解？该插件的入口是下面这样的：
```
hexo.extend.filter.register('before_post_render', require('./lib/logic'), 15);
```


另外你`hexo g`成功了吗？

**Comment by yehuohan** [comment]
这是从hexo clean到hexo g的过程：
先是生成目录
![1](https://user-images.githubusercontent.com/17680752/38235583-3b2648c2-3754-11e8-9437-fbd8986ce5a2.PNG)
然后开始生成html
![2](https://user-images.githubusercontent.com/17680752/38235585-3cf9e708-3754-11e8-8bad-4194bc63e85e.PNG)
![3](https://user-images.githubusercontent.com/17680752/38235588-3f5feef2-3754-11e8-9bb0-797ce5224e94.PNG)

整个过程并没有出现error之类的提示。

**Comment by yehuohan** [comment]
我在想是不是跟我用的主题[3-hexo](https://github.com/yelog/hexo-theme-3-hexo)冲突了，这个主题是直接提取所有的categories来生成分类(其它有的主题，可以在主题的_config.yml中直接设定分类)，加了自动按目录生成分类的插件后，两者会不会有冲突。

**Comment by xu-song** [comment]
# 关于 YAML header error
Error: [pandoc warning] YAML header is not an object "source" (line 3, column 1)

## 可能是`---`的影响 
我觉得，有可能是是你文件的写法，其中的`---`的影响。

[示例markdown文件](https://raw.githubusercontent.com/yehuohan/yehuohan.blog.src/master/source/_posts/%E6%9D%82%E8%AE%B0/%E5%9F%BA%E7%B1%BB%E6%8C%87%E9%92%88%E6%8C%87%E5%90%91%E6%B4%BE%E7%94%9F%E7%B1%BB%E5%AE%9E%E4%BE%8B%E5%9B%BE%E8%A7%A3.md)



## 即使不用`hexo-auto-category`插件，`hexo g`也有问题。
```
$ npm uninstall hexo-auto-category
$ hexo clean
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: [pandoc warning] YAML header is not an object "source" (line 3, column 1)

    at ChildProcess.<anonymous> (/home/xs/web/blog-dev/node_modules/hexo-renderer-pandoc/index.js:84:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
```

## 多加几个横线

测试通过

## 解决

- 方式一：你可以多加几个横线。
- 方式二：猜测是https://github.com/hexojs/hexo-front-matter的 issue。




# 关于重复generate的问题

仍然未重现

**Comment by yehuohan** [comment]
你的意思是这个影响了hexo对开头title, categories等信息的提取？
![1](https://user-images.githubusercontent.com/17680752/38237090-bde0e17e-3758-11e8-9ce0-e75e3eb200c3.PNG)

**Comment by yehuohan** [comment]
我刚才测试了一下，整个_post只留 `杂记/基类指针指向派生类实例图解` 这篇文章（_draft里的也全删了），按照hexo clean，再hexo g再hexo s的命令测试了：

开启auto-cagegory还是有相同问题：
![1](https://user-images.githubusercontent.com/17680752/38237997-20eb97f8-375b-11e8-8bb4-66cf6be55ad4.PNG)

不用auto-cagetory（在hexo的_config.yml里将auto-cagegory的enable设成false）问题就没了：
![2](https://user-images.githubusercontent.com/17680752/38238050-4b6cbac0-375b-11e8-8ef2-238dbe511053.png)

**Comment by xu-song** [comment]
en，应该是
- 你的项目不依赖`hexo-front-matter`，而这个插件依赖`hexo-front-matter`。 所以你`hexo g`没问题，打开auto-category报错。
- 我的project还有其他插件依赖`hexo-front-matter` (我用了hexo-abbrlink)，所以即使关掉auto-category也会报错。


你把横线加长点，再打开`auto_category`，试试。我这里没重现出你的问题，没出现`重复很多遍的问题`。所以只能试试，定位一下bug的地方

**update**

这个重复generate的问题，跟`---`没关系。我这儿是`hexo-renderer-pandoc`的markdown引擎的问题。

**Comment by yehuohan** [comment]
在前面的 `整个_post只留 杂记/基类指针指向派生类实例图解 这篇文章` 这个测试里，文章中除了开头的横线，没有使用其它横线了，那`---`不会对auto-category造成影响了吧？

**Comment by xu-song** [comment]
这个，不清楚。另外，hexo-auto-category 是静态生成category。
即**生成一次category之后，就暂时用不到了**。

你可以临时关掉auto-category，保证`hexo g` `hexo s` `hexo d` 能正常。后面我试试能否重现你的问题

**Comment by yehuohan** [comment]
好的，麻烦了。
开着auto-category只是预览时有点有小影响，对其它的部署没有影响。

**Comment by lqzhgood** [comment]
你这个不是死循环么~
server watch file~
然后你把 分类 写入文件。
继续触发  watch file 
继续把 分类写入文件。。。。。

应该写 分类的时候 判断是否和现在相同，如果相同不处理。

等会我提个PR吧。

**Comment by lqzhgood** [comment]
lz 记得把 npm 的也更新下~

**Comment by xu-song** [comment]
thanks, 已更新
