### ISSUE TITLE
How do I get this?

### ISSUE THREAD

**Issue by HeraKumi** [xu-song/hexo-auto-category#5]
On you're blog site you have page that displays all categorys how do I do that on my site, with the hexo theme https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/

**Comment by xu-song** [comment]
You can follow the project [README ](https://github.com/xu-song/hexo-auto-category#installation).
```
npm install hexo-auto-category --save
```
then config in your site `_config.yml`.  Any hexo theme can use this plugin.

**Comment by HeraKumi** [comment]
But it doesn’t state how to display all categories on a new page, you can see on my page here 

http://blog.lawli.me/

And I have read and followed your read me, and it did add categories to my post top section.

**Comment by xu-song** [comment]
Can show your logs while `hexo g` ?

Generally it will generate logs as follows:


# For example

For the following file structure 

```sh
$ tree
.
└── _post
    ├── linux
    │   └── network.md
    └── programing
        └── java
            └── thread.md

```

It will generate logs as follows:

```
$ hexo clean
$ hexo g
INFO  Generated: categories [linux] for post [network]
INFO  Generated: categories [programing,java] for post [thread]
```

If you didn't see these logs, maybe you miss some configuration.

**Important**:

configure this plugin in site _config.yml,  **not theme config**

**Comment by HeraKumi** [comment]
no not that this.
https://streamango.com/f/qtmdbfpknoadfcpm/2018-07-25_23-17-36_mkv

**Comment by xu-song** [comment]
?

**Comment by HeraKumi** [comment]
How did you get a separate page to display every single category?

**Comment by xu-song** [comment]
https://github.com/hexojs/hexo-generator-category

you need to install this plugin

**Comment by HeraKumi** [comment]
I have done that, but do I need to create a new page but then what do I put in the index.md to get the category to show up.

**Comment by HeraKumi** [comment]
Thanks I figured it out. <3

**Comment by xu-song** [comment]
welcome
