### ISSUE TITLE
分类时有Bug

### ISSUE THREAD

**Issue by sshwy** [xu-song/hexo-auto-category#6]
请开发者见我博客
https://sshwy.gitee.io/2018/10/06/99/

**Comment by xu-song** [comment]
## 文件名不作为category


```
_post/Programming/Python/排序.md
```
你提到的这个例子，会生成标签
```
categories:
  - Programming
  - Python
```
文件名不作为category应该更符合大众需求吧

## 关于空分类
类似以下的例子，也可以不生成`[]`作为category。这个应该影响不大
```
INFO  Generated: categories [] for post [C++常数优化]
```

## 关于hexo s的无限循环

是，hexo s的时候会有问题。我也不知道为什么。
所以我就一直不用hexo s，直接hexo d。

囧o(╯□╰)o

**欢迎PR**

**Comment by sshwy** [comment]
## 我不是说文件名要作为category
我也不会把文件名作为category

其实我的重点在于，你的以下代码
```
var categories = data.slug.split('/');
```
有问题。
- **正常情况**下，它解析了`_post/Programming/Python/排序.md`后，category会变成["Programming","Python","排序"]，然后在接下来的代码中，用前2个元素（去掉最后一个）来生成标签：
```
categories:
  - Programming
  - Python
```

- 然而在我这里generator的时候，categories变成了`["Programming-Python-排序"]`，然后你再用它生成category，就是空的：
```
categories: []
```
就会长成这样。。。。。
您还是有时间修复一下这个Bug吧
还有那个`hexo s`的Bug。。。不用`hexo s`我很难受的。。。

**Comment by xu-song** [comment]
哦，你说的这种情况，我没遇到过。是`data.slug`获取的问题吗？
```js
console.log(data.slug)    //  Programming/Python/排序
console.log(data.source)  //  _post/Programming/Python/排序.md
var categories = data.slug.split('/');  // 正常
```

你那里的  `data.slug`解析出来不是这个值吗？可能是hexo版本问题，保险起见 可以采用`data.source`

## hexo s 遇到的问题

我暂时也没找到原因，o(╯□╰)o
