### ISSUE TITLE
建议加个minDepth参数

### ISSUE THREAD

**Issue by LengSword** [xu-song/hexo-auto-category#7]
```javascript
var minDepth = this.config.auto_category.minDepth || 0;

...

tmpPost.categories = categories.slice(1+Math.min(minDepth, categories.length-2), 1+Math.min(depth, categories.length-2));
```

**Comment by xu-song** [comment]
默认的depth，是指的`max_depth`的意思。minDepth没多大必要性吧，太小众了吧。

我的建议是，还不如调整自己的目录结构

**Comment by LengSword** [comment]
好吧，不过还有个问题，就是文章目录太长会导致目录卡片覆盖遮住友链卡片

**Comment by xu-song** [comment]
是css 样式的问题吗？ 

简单解决的话，目录名短一些，或者设置depth参数

**Comment by LengSword** [comment]
不是那个文件目录，就是文章TOC目录太长的问题

**Comment by xu-song** [comment]
TOC？跟文件目录没关系吧。有例子吗

**Comment by LengSword** [comment]
例子啊...
就是比如我在一个markdown文件里写很多二级三级标题，这样TOC卡片的长度就会很长，然后你上下移动的时候因为目录是会跟随着你当前阅读的位置移动的，就遮住了友链的那卡片了

**Comment by xu-song** [comment]
这个跟主题相关的，要看你用的什么主题了

**Comment by LengSword** [comment]
问错repo了...傻逼了，那我关issue了
